### ISSUE TITLE
Autostart behavior - a lot of failed device creation calls in short time

### ISSUE THREAD

**Issue by smitterl** [mdevctl/mdevctl#53]
Discussed with @jonner to bring this up for review:
While testing the autostart behavior we see that devices are retried after start fails in very short intervals. Also, starts are seemingly tried even after a device has been started successfully. Please note, that the autostart itself succeeds.

I'm wondering if in a bigger number of configured devices this could lead to performance issues. Please, note that the behavior seems to depend on the very mdev type (comparing here vfio-ccw and vfio-ap). The following is the output when rebooting a system with two devices defined for autostart that's defined through a callout script like:

```bash
if [[ "$event" == "post" ]] && [[ "$action" == "start" ]]; then
	echo "$(date +%M:%S:%N) $type $event $action $state $parent $uuid $json" >> /tmp/mdevctl.out
fi
```

```
15:41:874777186 vfio_ap-passthrough post start success matrix cbfa3222-3db3-49f0-a031-52c5f8ecb2e3 {"mdev_type":"vfio_ap-passthrough","start":"auto","attrs":[]}
15:41:876598750 vfio_ap-passthrough post start failure matrix cbfa3222-3db3-49f0-a031-52c5f8ecb2e3 {"mdev_type":"vfio_ap-passthrough","start":"auto","attrs":[]}
15:41:886164875 vfio_ap-passthrough post start failure matrix cbfa3222-3db3-49f0-a031-52c5f8ecb2e3 {"mdev_type":"vfio_ap-passthrough","start":"auto","attrs":[]}
15:42:276290374 vfio_ccw-io post start failure 0.0.26aa 1cc0b78d-46d1-47dd-9ac3-78425d284979 {"mdev_type":"vfio_ccw-io","start":"auto","attrs":[]}
15:42:299486188 vfio_ap-passthrough post start failure matrix cbfa3222-3db3-49f0-a031-52c5f8ecb2e3 {"mdev_type":"vfio_ap-passthrough","start":"auto","attrs":[]}
15:42:355402687 vfio_ccw-io post start failure 0.0.26aa 1cc0b78d-46d1-47dd-9ac3-78425d284979 {"mdev_type":"vfio_ccw-io","start":"auto","attrs":[]}
15:42:414190627 vfio_ap-passthrough post start failure matrix cbfa3222-3db3-49f0-a031-52c5f8ecb2e3 {"mdev_type":"vfio_ap-passthrough","start":"auto","attrs":[]}
15:42:423196749 vfio_ap-passthrough post start failure matrix cbfa3222-3db3-49f0-a031-52c5f8ecb2e3 {"mdev_type":"vfio_ap-passthrough","start":"auto","attrs":[]}
15:42:431242875 vfio_ccw-io post start success 0.0.26aa 1cc0b78d-46d1-47dd-9ac3-78425d284979 {"mdev_type":"vfio_ccw-io","start":"auto","attrs":[]}
```

**Comment by jonner** [comment]
As I mentioned briefly when we discussed this, the fact that this is called multiple times due to udev itself. The udev rule that mdevctl provides is pretty "dumb". It is triggered by "add" events that are emitted by udev. If udev emits multiple "add" events for a given parent device, the mdevctl rule will be triggered multiple times. It's not that it is "retrying" anything, exactly. It's just being triggered again by another udev event. Exactly why we are getting multiple udev events for the same parent device, I don't know. It might be something specific to the hardware you have. Or maybe we're not matching the event specifically enough.

The udev rule is supposed to log stdout and stderr to the syslog. Do you have anything in your syslog about the failures? I suspect that the `cbfa3222-3db3-49f0-a031-52c5f8ecb2e3` device succeeds and then subsequently fails repeatedly because it has already been started (you might see an error message saying "Device already exists"). I'm not sure about the failures for the other device.

**Comment by jonner** [comment]
Closing for now since I don't think it's really an issue in mdevctl. Please re-open if you have further information.
